from typing import overload

class Match:
    @overload
    def group(self, group: int | str = 0, /) -> str | None: ...
    @overload
    def group(self, group1: int | str, group2: int | str, /, *groups: int | str) -> tuple[str | None, ...]: ...
    def groups(self, default: str | None = None) -> tuple[str | None, ...]: ...

class Options:
    log_errors: bool
    max_mem: int
    never_capture: bool

class Pattern:
    @property
    def groups(self) -> int: ...
    def fullmatch(self, text: str, pos: int | None = None, endpos: int | None = None) -> Match | None: ...
    def search(self, text: str, pos: int | None = None, endpos: int | None = None) -> Match | None: ...

class error(Exception): ...

def compile(pattern: str | Pattern, options: Options | None = None) -> Pattern: ...
def escape(pattern: str) -> str: ...
