project:
  metadata:
    committee: tooling
    name: Apache Trusted Releases
    description: ATR is a platform through which committees of Apache Software Foundation (ASF) projects can make official ASF software releases. Official ASF releases are endorsed as an "act of the Foundation". It is therefore important that the foundation - its board, members, committees, and contributors - and the general public can have confidence in the releases.
    short_description: A platform for making official ASF software releases.
    homepage: https://tooling.apache.org/trusted-releases.html
    lifecycle_page: https://tooling.apache.org/trusted-releases.html
    download_page: https://github.com/apache/tooling-trusted-releases
    bug_database: https://github.com/apache/tooling-trusted-releases/issues
    mailing_lists: https://tooling.apache.org/volunteer.html
    repositories:
      - git+ssh://git@github.com:apache/tooling-trusted-releases.git
    standards:
      - https://owasp.org/www-project-application-security-verification-standard/
    categories:
      - build-management
    programming_languages:
      - python
  features:
    atr_sync: true

github:
  description: "Apache Trusted Releases"
  homepage: https://tooling.apache.org/
  del_branch_on_merge: true
  features:
    issues: true
    projects: true
  enabled_merge_buttons:
    squash:  true
    squash_commit_message: DEFAULT
    merge:   false
    rebase:  true
  custom_subjects:
    new_pr: "[PR] {title} ({repository})"
    close_pr: "Re: [PR] {title} ({repository})"
    comment_pr: "Re: [PR] {title} ({repository})"
    merge_pr: "Re: [PR] {title} ({repository})"
    new_issue: "[I] {title} ({repository})"
    comment_issue: "Re: [I] {title} ({repository})"
    close_issue: "Re: [I] {title} ({repository})"
    catchall: "[GH] {title} ({repository})"
  protected_branches:
    main: {}

notifications:
  commits:      commits@tooling.apache.org
  issues:       issues@tooling.apache.org
  pullrequests: issues@tooling.apache.org
