# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

import dataclasses
import datetime
import enum
import pathlib
from collections.abc import Callable

import atr.classify as classify
import atr.models.schema as schema
import atr.models.sql as sql
import atr.storage.outcome as outcome


@dataclasses.dataclass
class CheckerStats:
    checker: str
    success_count: int
    warning_count: int
    failure_count: int
    blocker_count: int
    warning_files: dict[str, int]
    failure_files: dict[str, int]
    blocker_files: dict[str, int]


@dataclasses.dataclass
class CheckResults:
    primary_results_list: list[sql.CheckResult]
    member_results_list: dict[str, list[sql.CheckResult]]
    ignored_checks: list[sql.CheckResult]


class KeyStatus(enum.Flag):
    PARSED = 0
    INSERTED = enum.auto()
    LINKED = enum.auto()
    INSERTED_AND_LINKED = INSERTED | LINKED


class Key(schema.Strict):
    status: KeyStatus
    key_model: sql.PublicSigningKey


@dataclasses.dataclass
class LinkedCommittee:
    name: str
    autogenerated_keys_file: outcome.Outcome[str]


class PathInfo(schema.Strict):
    checker_stats: list[CheckerStats] = schema.factory(list)
    errors: dict[pathlib.Path, list[sql.CheckResult]] = schema.factory(dict)
    file_types: dict[pathlib.Path, classify.FileType] = schema.factory(dict)
    ignored_errors: list[sql.CheckResult] = schema.factory(list)
    ignored_warnings: list[sql.CheckResult] = schema.factory(list)
    successes: dict[pathlib.Path, list[sql.CheckResult]] = schema.factory(dict)
    warnings: dict[pathlib.Path, list[sql.CheckResult]] = schema.factory(dict)


class PersonalAccessTokenSafe(schema.Strict):
    asfuid: str
    created: datetime.datetime
    expires: datetime.datetime
    id: int
    label: str | None
    last_used: datetime.datetime | None

    @classmethod
    def from_sql(cls, token: sql.PersonalAccessToken) -> "PersonalAccessTokenSafe":
        if token.id is None:
            raise ValueError("PAT must have an ID before being returned")
        return cls(
            id=token.id,
            asfuid=token.asfuid,
            created=token.created,
            expires=token.expires,
            label=token.label,
            last_used=token.last_used,
        )


@dataclasses.dataclass
class ChecksSubset:
    checks: list[sql.CheckResult]
    info: PathInfo
    match_ignore: Callable[[sql.CheckResult], bool]


class PublicKeyError(Exception):
    def __init__(self, key: Key, original_error: Exception):
        self.__key = key
        self.__original_error = original_error

    def __str__(self) -> str:
        return f"PublicKeyError: {self.__original_error}"

    @property
    def key(self) -> Key:
        return self.__key

    @property
    def original_error(self) -> Exception:
        return self.__original_error


class FailedError(Exception):
    pass


class PhaseMismatchError(FailedError):
    pass
