"""mass rename name => key

Revision ID: 0059_2026.03.16_2c8e4716
Revises: 0058_2026.03.12_2ebee77e
Create Date: 2026-03-16 18:35:29.940455+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlmodel
import atr.models.sql
import sqlalchemy as sa

# Revision identifiers, used by Alembic
revision: str = '0059_2026.03.16_2c8e4716'
down_revision: Union[str, None] = '0058_2026.03.12_2ebee77e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkresult', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_key', sa.String(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_checkresult_release_name'))
        batch_op.create_index(batch_op.f('ix_checkresult_release_key'), ['release_key'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_checkresult_release_name_release'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_checkresult_release_key_release'), 'release', ['release_key'], ['key'], ondelete='CASCADE')
        batch_op.drop_column('release_name')

    with op.batch_alter_table('checkresultignore', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_key', sa.String(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_checkresultignore_project_name_project'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_checkresultignore_project_key_project'), 'project', ['project_key'], ['key'])
        batch_op.drop_column('project_name')

    with op.batch_alter_table('committee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('parent_committee_key', sa.String(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('uq_committee_name'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_committee_key'), ['key'])
        batch_op.drop_constraint(batch_op.f('fk_committee_parent_committee_name_committee'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_committee_parent_committee_key_committee'), 'committee', ['parent_committee_key'], ['key'])
        batch_op.drop_column('full_name')
        batch_op.drop_column('parent_committee_name')

    with op.batch_alter_table('distribution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_key', sa.String(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_distribution_release_name'))
        batch_op.create_index(batch_op.f('ix_distribution_release_key'), ['release_key'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_distribution_release_name_release'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_distribution_release_key_release'), 'release', ['release_key'], ['key'], ondelete='CASCADE')
        batch_op.drop_column('release_name')

    with op.batch_alter_table('keylink', schema=None) as batch_op:
        batch_op.add_column(sa.Column('committee_key', sa.String(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_keylink_committee_name_committee'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_keylink_committee_key_committee'), 'committee', ['committee_key'], ['key'])
        batch_op.drop_column('committee_name')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('super_project_key', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('committee_key', sa.String(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('uq_project_name'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_project_key'), ['key'])
        batch_op.drop_constraint(batch_op.f('fk_project_committee_name_committee'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_project_super_project_name_project'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_project_super_project_key_project'), 'project', ['super_project_key'], ['key'])
        batch_op.create_foreign_key(batch_op.f('fk_project_committee_key_committee'), 'committee', ['committee_key'], ['key'])
        batch_op.drop_column('full_name')
        batch_op.drop_column('super_project_name')
        batch_op.drop_column('committee_name')

    with op.batch_alter_table('quarantined', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_key', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('prior_revision_key', sa.String(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_quarantined_release_name'))
        batch_op.create_index(batch_op.f('ix_quarantined_release_key'), ['release_key'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_quarantined_release_name_release'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_quarantined_release_key_release'), 'release', ['release_key'], ['key'], ondelete='CASCADE')
        batch_op.drop_column('release_name')
        batch_op.drop_column('prior_revision_name')

    with op.batch_alter_table('release', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('project_key', sa.String(), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_release_name'), type_='unique')
        batch_op.drop_constraint(batch_op.f('unique_project_version'), type_='unique')
        batch_op.create_unique_constraint('unique_project_version', ['project_key', 'version'])
        batch_op.create_unique_constraint(batch_op.f('uq_release_key'), ['key'])
        batch_op.drop_constraint(batch_op.f('fk_release_project_name_project'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_release_project_key_project'), 'project', ['project_key'], ['key'])
        batch_op.drop_column('name')
        batch_op.drop_column('project_name')

    with op.batch_alter_table('revision', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('release_key', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('parent_key', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('merge_base_revision_key', sa.String(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_revision_name'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_revision_release_number'), type_='unique')
        batch_op.create_unique_constraint('uq_revision_release_number', ['release_key', 'number'])
        batch_op.drop_constraint(batch_op.f('uq_revision_release_seq'), type_='unique')
        batch_op.create_unique_constraint('uq_revision_release_seq', ['release_key', 'seq'])
        batch_op.create_unique_constraint(batch_op.f('uq_revision_key'), ['key'])
        batch_op.drop_constraint(batch_op.f('fk_revision_release_name_release'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_revision_parent_name_revision'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_revision_release_key_release'), 'release', ['release_key'], ['key'])
        batch_op.create_foreign_key(batch_op.f('fk_revision_parent_key_revision'), 'revision', ['parent_key'], ['key'])
        batch_op.drop_column('name')
        batch_op.drop_column('parent_name')
        batch_op.drop_column('merge_base_revision_name')
        batch_op.drop_column('release_name')

    with op.batch_alter_table('revisioncounter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_key', sa.String(), nullable=False))
        batch_op.drop_column('release_name')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_key', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('version_key', sa.String(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_task_version_name'))
        batch_op.create_index(batch_op.f('ix_task_version_key'), ['version_key'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_task_project_key_project'), 'project', ['project_key'], ['key'])
        batch_op.drop_column('project_name')
        batch_op.drop_column('version_name')

    with op.batch_alter_table('workflowsshkey', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_key', sa.String(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_workflowsshkey_project_name'))
        batch_op.create_index(batch_op.f('ix_workflowsshkey_project_key'), ['project_key'], unique=False)
        batch_op.drop_column('project_name')

    with op.batch_alter_table('workflowstatus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_key', sa.String(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_workflowstatus_project_name'))
        batch_op.create_index(batch_op.f('ix_workflowstatus_project_key'), ['project_key'], unique=False)
        batch_op.drop_column('project_name')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflowstatus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_name', sa.VARCHAR(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_workflowstatus_project_key'))
        batch_op.create_index(batch_op.f('ix_workflowstatus_project_name'), ['project_name'], unique=False)
        batch_op.drop_column('project_key')

    with op.batch_alter_table('workflowsshkey', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_name', sa.VARCHAR(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_workflowsshkey_project_key'))
        batch_op.create_index(batch_op.f('ix_workflowsshkey_project_name'), ['project_name'], unique=False)
        batch_op.drop_column('project_key')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('project_name', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_task_project_key_project'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'project', ['project_name'], ['name'])
        batch_op.drop_index(batch_op.f('ix_task_version_key'))
        batch_op.create_index(batch_op.f('ix_task_version_name'), ['version_name'], unique=False)
        batch_op.drop_column('version_key')
        batch_op.drop_column('project_key')

    with op.batch_alter_table('revisioncounter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_name', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('release_key')

    with op.batch_alter_table('revision', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('merge_base_revision_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('parent_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_revision_parent_key_revision'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_revision_release_key_release'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_revision_parent_name_revision'), 'revision', ['parent_name'], ['name'])
        batch_op.create_foreign_key(batch_op.f('fk_revision_release_name_release'), 'release', ['release_name'], ['name'])
        batch_op.drop_constraint(batch_op.f('uq_revision_key'), type_='unique')
        batch_op.drop_constraint('uq_revision_release_seq', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_revision_release_seq'), ['release_name', 'seq'])
        batch_op.drop_constraint('uq_revision_release_number', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_revision_release_number'), ['release_name', 'number'])
        batch_op.create_unique_constraint(batch_op.f('uq_revision_name'), ['name'])
        batch_op.drop_column('merge_base_revision_key')
        batch_op.drop_column('parent_key')
        batch_op.drop_column('release_key')
        batch_op.drop_column('key')

    with op.batch_alter_table('release', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_release_project_key_project'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_release_project_name_project'), 'project', ['project_name'], ['name'])
        batch_op.drop_constraint(batch_op.f('uq_release_key'), type_='unique')
        batch_op.drop_constraint('unique_project_version', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('unique_project_version'), ['project_name', 'version'])
        batch_op.create_unique_constraint(batch_op.f('uq_release_name'), ['name'])
        batch_op.drop_column('project_key')
        batch_op.drop_column('key')

    with op.batch_alter_table('quarantined', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prior_revision_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('release_name', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_quarantined_release_key_release'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_quarantined_release_name_release'), 'release', ['release_name'], ['name'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_quarantined_release_key'))
        batch_op.create_index(batch_op.f('ix_quarantined_release_name'), ['release_name'], unique=False)
        batch_op.drop_column('prior_revision_key')
        batch_op.drop_column('release_key')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('committee_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('super_project_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_project_committee_key_committee'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_project_super_project_key_project'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_project_super_project_name_project'), 'project', ['super_project_name'], ['name'])
        batch_op.create_foreign_key(batch_op.f('fk_project_committee_name_committee'), 'committee', ['committee_name'], ['name'])
        batch_op.drop_constraint(batch_op.f('uq_project_key'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_project_name'), ['name'])
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('committee_key')
        batch_op.drop_column('super_project_key')
        batch_op.drop_column('key')

    with op.batch_alter_table('keylink', schema=None) as batch_op:
        batch_op.add_column(sa.Column('committee_name', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_keylink_committee_key_committee'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_keylink_committee_name_committee'), 'committee', ['committee_name'], ['name'])
        batch_op.drop_column('committee_key')

    with op.batch_alter_table('distribution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_name', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_distribution_release_key_release'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_distribution_release_name_release'), 'release', ['release_name'], ['name'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_distribution_release_key'))
        batch_op.create_index(batch_op.f('ix_distribution_release_name'), ['release_name'], unique=False)
        batch_op.drop_column('release_key')

    with op.batch_alter_table('committee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_committee_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_committee_parent_committee_key_committee'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_committee_parent_committee_name_committee'), 'committee', ['parent_committee_name'], ['name'])
        batch_op.drop_constraint(batch_op.f('uq_committee_key'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_committee_name'), ['name'])
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('parent_committee_key')
        batch_op.drop_column('key')

    with op.batch_alter_table('checkresultignore', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_name', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_checkresultignore_project_key_project'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_checkresultignore_project_name_project'), 'project', ['project_name'], ['name'])
        batch_op.drop_column('project_key')

    with op.batch_alter_table('checkresult', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_name', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_checkresult_release_key_release'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_checkresult_release_name_release'), 'release', ['release_name'], ['name'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_checkresult_release_key'))
        batch_op.create_index(batch_op.f('ix_checkresult_release_name'), ['release_name'], unique=False)
        batch_op.drop_column('release_key')

    # ### end Alembic commands ###
