"""add workflowsshkey revoked column

Revision ID: 0067_2026.04.14_bbfd41d3
Revises: 0066_2026.04.13_a7d14b22
Create Date: 2026-04-14 16:07:47.559110+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Revision identifiers, used by Alembic
revision: str = "0067_2026.04.14_bbfd41d3"
down_revision: str | None = "0066_2026.04.13_a7d14b22"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workflowsshkey", schema=None) as batch_op:
        batch_op.add_column(sa.Column("revoked", sa.Boolean(), nullable=False, server_default=sa.text("0")))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workflowsshkey", schema=None) as batch_op:
        batch_op.drop_column("revoked")

    # ### end Alembic commands ###
