# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

from __future__ import annotations

from typing import Final

LICENSES: Final[dict[str, list[str]]] = {
    "CATEGORY_A_LICENSES": [
        "0BSD",
        "AFL-3.0",
        "APAFML",
        "Apache-1.1",
        "Apache-2.0",
        "BSD-2-Clause",
        "BSD-3-Clause",
        "BSD-3-Clause-LBNL",
        "BSL-1.0",
        "Bitstream-Vera",
        "BlueOak-1.0.0",
        "CC-PDDC",
        "CC-PDM-1.0",
        "CC0-1.0",
        "DOC",
        "EPICS",
        "FSFAP",
        "HPND",
        "ICU",
        "ISC",
        "Libpng",
        "LicenseRef-COLT-CERN",
        "LicenseRef-CupPG",
        "LicenseRef-DOM4J",
        "LicenseRef-ECMA-OOXML-XSD",
        "LicenseRef-Google-AIPG",
        "LicenseRef-MX4J",
        "LicenseRef-Open-Grid-Forum",
        "LicenseRef-PIL",
        "LicenseRef-Romantic-WTFPL",
        "LicenseRef-SCA-Spec",
        "LicenseRef-W3C-CCLA",
        "MIT",
        "MIT-0",
        "MS-PL",
        "MulanPSL-2.0",
        "NCSA",
        "OGL-UK-3.0",
        "PHP-3.01",
        "PostgreSQL",
        "Python-2.0",
        "PSF-2.0",
        "SMLNJ",
        "TCL",
        "UPL-1.0",
        "Unicode-DFS-2016",
        "Unlicense",
        "W3C",
        "WTFPL",
        "Xnet",
        "ZPL-2.0",
        "Zlib",
    ],
    "CATEGORY_B_LICENSES": [
        "CC-BY-2.5",
        "CC-BY-3.0",
        "CC-BY-4.0",
        "CC-BY-SA-2.5",
        "CC-BY-SA-3.0",
        "CC-BY-SA-4.0",
        "CDDL-1.0",
        "CDDL-1.1",
        "CPL-1.0",
        "EPL-1.0",
        "EPL-2.0",
        "ErlPL-1.1",
        "IPA",
        "IPL-1.0",
        "LicenseRef-CMaps-Fonts",
        "LicenseRef-JARs-Additional",
        "LicenseRef-JCR-API",
        "LicenseRef-UnRAR",
        "LicenseRef-WSDL-SFL",
        "MPL-1.0",
        "MPL-1.1",
        "MPL-2.0",
        "OFL-1.1",
        "OSL-3.0",
        "Ruby",
        "SPL-1.0",
        "Ubuntu-font-1.0",
    ],
    "CATEGORY_X_LICENSES": [
        "AGPL-3.0-only",
        "AGPL-3.0-or-later",
        "BSD-4-Clause",
        "BSD-4-Clause-UC",
        "BUSL-1.1",
        "CC-BY-NC-4.0",
        "CPOL-1.02",
        "GPL-1.0-only",
        "GPL-1.0-or-later",
        "GPL-2.0-only",
        "GPL-2.0-only WITH Classpath-exception-2.0",
        "GPL-2.0-or-later",
        "GPL-2.0-or-later WITH Classpath-exception-2.0",
        "GPL-3.0-only",
        "GPL-3.0-only WITH Classpath-exception-2.0",
        "GPL-3.0-or-later",
        "GPL-3.0-or-later WITH Classpath-exception-2.0",
        "JSON",
        "LGPL-2.0-only",
        "LGPL-2.0-or-later",
        "LGPL-2.1-only",
        "LGPL-2.1-or-later",
        "LGPL-3.0-only",
        "LGPL-3.0-or-later",
        "LicenseRef-Amazon-Software-License",
        "LicenseRef-BCL",
        "LicenseRef-Booz-Allen-Public-License",
        "LicenseRef-Commons-Clause-1.0",
        "LicenseRef-Confluent-Community-1.0",
        "LicenseRef-DBAD",
        "LicenseRef-Facebook-BSD-Patents",
        "LicenseRef-Intel-SSL",
        "LicenseRef-JSR-275",
        "LicenseRef-Java-SDK-for-Satori-RTM",
        "LicenseRef-Redis-Source-Available",
        "LicenseRef-Solipsistic-Eclipse-Public-License",
        "LicenseRef-Sun-Community-Source-3.0",
        "MS-LPL",
        "NPL-1.0",
        "NPL-1.1",
        "QPL-1.0",
        "SSPL-1.0",
        "Sleepycat",
    ],
}

# The SPDX name for each categorised licence, so that a component declaring its licence by
# name instead of by identifier can still be categorised
LICENSE_NAMES: Final[dict[str, str]] = {
    "0BSD": "BSD Zero Clause License",
    "AFL-3.0": "Academic Free License v3.0",
    "AGPL-3.0-only": "GNU Affero General Public License v3.0 only",
    "AGPL-3.0-or-later": "GNU Affero General Public License v3.0 or later",
    "Apache-1.1": "Apache License 1.1",
    "Apache-2.0": "Apache License 2.0",
    "APAFML": "Adobe Postscript AFM License",
    "Bitstream-Vera": "Bitstream Vera Font License",
    "BlueOak-1.0.0": "Blue Oak Model License 1.0.0",
    "BSD-2-Clause": 'BSD 2-Clause "Simplified" License',
    "BSD-3-Clause": 'BSD 3-Clause "New" or "Revised" License',
    "BSD-3-Clause-LBNL": "Lawrence Berkeley National Labs BSD variant license",
    "BSD-4-Clause": 'BSD 4-Clause "Original" or "Old" License',
    "BSD-4-Clause-UC": "BSD-4-Clause (University of California-Specific)",
    "BSL-1.0": "Boost Software License 1.0",
    "BUSL-1.1": "Business Source License 1.1",
    "CC-BY-2.5": "Creative Commons Attribution 2.5 Generic",
    "CC-BY-3.0": "Creative Commons Attribution 3.0 Unported",
    "CC-BY-4.0": "Creative Commons Attribution 4.0 International",
    "CC-BY-NC-4.0": "Creative Commons Attribution Non Commercial 4.0 International",
    "CC-BY-SA-2.5": "Creative Commons Attribution Share Alike 2.5 Generic",
    "CC-BY-SA-3.0": "Creative Commons Attribution Share Alike 3.0 Unported",
    "CC-BY-SA-4.0": "Creative Commons Attribution Share Alike 4.0 International",
    "CC-PDDC": "Creative Commons Public Domain Dedication and Certification",
    "CC-PDM-1.0": "Creative    Commons Public Domain Mark 1.0 Universal",
    "CC0-1.0": "Creative Commons Zero v1.0 Universal",
    "CDDL-1.0": "Common Development and Distribution License 1.0",
    "CDDL-1.1": "Common Development and Distribution License 1.1",
    "CPL-1.0": "Common Public License 1.0",
    "CPOL-1.02": "Code Project Open License 1.02",
    "DOC": "DOC License",
    "EPICS": "EPICS Open License",
    "EPL-1.0": "Eclipse Public License 1.0",
    "EPL-2.0": "Eclipse Public License 2.0",
    "ErlPL-1.1": "Erlang Public License v1.1",
    "FSFAP": "FSF All Permissive License",
    "GPL-1.0-only": "GNU General Public License v1.0 only",
    "GPL-1.0-or-later": "GNU General Public License v1.0 or later",
    "GPL-2.0-only": "GNU General Public License v2.0 only",
    "GPL-2.0-or-later": "GNU General Public License v2.0 or later",
    "GPL-3.0-only": "GNU General Public License v3.0 only",
    "GPL-3.0-or-later": "GNU General Public License v3.0 or later",
    "HPND": "Historical Permission Notice and Disclaimer",
    "ICU": "ICU License",
    "IPA": "IPA Font License",
    "IPL-1.0": "IBM Public License v1.0",
    "ISC": "ISC License",
    "JSON": "JSON License",
    "LGPL-2.0-only": "GNU Library General Public License v2 only",
    "LGPL-2.0-or-later": "GNU Library General Public License v2 or later",
    "LGPL-2.1-only": "GNU Lesser General Public License v2.1 only",
    "LGPL-2.1-or-later": "GNU Lesser General Public License v2.1 or later",
    "LGPL-3.0-only": "GNU Lesser General Public License v3.0 only",
    "LGPL-3.0-or-later": "GNU Lesser General Public License v3.0 or later",
    "Libpng": "libpng License",
    "MIT": "MIT License",
    "MIT-0": "MIT No Attribution",
    "MPL-1.0": "Mozilla Public License 1.0",
    "MPL-1.1": "Mozilla Public License 1.1",
    "MPL-2.0": "Mozilla Public License 2.0",
    "MS-LPL": "Microsoft Limited Public License",
    "MS-PL": "Microsoft Public License",
    "MulanPSL-2.0": "Mulan Permissive Software License, Version 2",
    "NCSA": "University of Illinois/NCSA Open Source License",
    "NPL-1.0": "Netscape Public License v1.0",
    "NPL-1.1": "Netscape Public License v1.1",
    "OFL-1.1": "SIL Open Font License 1.1",
    "OGL-UK-3.0": "Open Government Licence v3.0",
    "OSL-3.0": "Open Software License 3.0",
    "PHP-3.01": "PHP License v3.01",
    "PostgreSQL": "PostgreSQL License",
    "PSF-2.0": "Python Software Foundation License 2.0",
    "Python-2.0": "Python License 2.0",
    "QPL-1.0": "Q Public License 1.0",
    "Ruby": "Ruby License",
    "Sleepycat": "Sleepycat License",
    "SMLNJ": "Standard ML of New Jersey License",
    "SPL-1.0": "Sun Public License v1.0",
    "SSPL-1.0": "Server Side Public License, v 1",
    "TCL": "TCL/TK License",
    "Ubuntu-font-1.0": "Ubuntu Font Licence v1.0",
    "Unicode-DFS-2016": "Unicode License Agreement - Data Files and Software (2016)",
    "Unlicense": "The Unlicense",
    "UPL-1.0": "Universal Permissive License v1.0",
    "W3C": "W3C Software Notice and License (2002-12-31)",
    "WTFPL": "Do What The F*ck You Want To Public License",
    "Xnet": "X.Net License",
    "Zlib": "zlib License",
    "ZPL-2.0": "Zope Public License 2.0",
}

CATEGORY_A_LICENSES_FOLD: Final[frozenset[str]] = frozenset(
    value.casefold() for value in LICENSES["CATEGORY_A_LICENSES"]
)

CATEGORY_B_LICENSES_FOLD: Final[frozenset[str]] = frozenset(
    value.casefold() for value in LICENSES["CATEGORY_B_LICENSES"]
)

CATEGORY_X_LICENSES_FOLD: Final[frozenset[str]] = frozenset(
    value.casefold() for value in LICENSES["CATEGORY_X_LICENSES"]
)
